### ISSUE TITLE
score depends on input file size

### ISSUE THREAD

**Issue by daald** [bbc/audio-offset-finder#19]
First of all, this algorithm is very nice and close to what I'm looking for. Unfortunately, I have a problem with the score.

An example with my data:

- I have an input file of 1 hour length and a sample to search of 20 seconds, the score is around 17.
- If I extract the relevant part of the input file, plus some extra seconds before and after, the score of the same part of the original file goes down to 6.

I had expected that the score in this example is somehow stable, no matter how long the input file is, but when I read the `cross_correlation` function and how `correl_nframes` is calculated, it is clear why this is not the case.

Btw for me it's not clear why `correl_nframes` limits itself to `2000`, and even more the `/ 3`.

I wonder if `score = (c[max_k_index] - np.mean(c)) / np.std(c)` could be replaced by something which is more stable in a use case as stated above. unfortunately, I don't have an idea what metrics are best to use to get something "standardized" for most use cases

**Comment by stephenjolly** [comment]
The standard score (https://en.wikipedia.org/wiki/Standard_score) of the cross-correlation is a measure of the prominence of the correlation peak (if one exists) above the "background noise" of low-correlation audio offsets.  

Without knowing anything about your audio files, I can't say for certain what the cause of the score reduction is with the shorter audio, but the implication is that the correlation peak is less clear - by definition, because either the mean or the standard deviation of the cross-correlations is greater.

My suggestion would be to use the "plots" branch of the repository (currently waiting to be reviewed before merging with master) and use the --plot option to take a look at the graphical representation of the cross-correlations at different offsets - they should provide a better understanding of why the peak is not as prominent with the shorter audio files.

correl_nframes is limited to 2000 as a way to prevent the processing time from growing super-linearly with longer audio files.  It's a trade-off intended to give adequate results for most use cases.  The /3 factor is there to nudge the processing  time vs accuracy trade-off a bit closer to the former for mid-length input files.  Neither figure is based on much more than instinct and (necessarily limited) personal experience though - feel free to experiment.

If you can share more details of your use case (including why it's important to repeat the search with a smaller range, and with a directly comparable metric for the two results), it would be interesting to hear them.

**Comment by daald** [comment]
[example-files.zip](https://github.com/bbc/audio-offset-finder/files/8606360/example-files.zip)
Due to licence restrictions, I'm not allowed to publish my original files. But I created some new files using audacity:
- sample.mp3 is a 10s file which contains artificial sound, this is the one to find
- master-long.mp3 is a 10 minutes file with noise. in the middle, sample.mp3 is mixed into this noise
- master-short.mp3 is an extract of the area where sample.mp3 is mixed in. it has 18s length. even the noise is the same in both files

Graphically:
- sample.mp3  AAA
- master-long.mp3 xxxxxxxxxxxxxxxxxxaaaxxxxxxxxxxxxxxxxxxxx
- master-short.mp3 xxaaaxx

Results:
```
audio-offset-finder --find-offset-of ../sample.mp3 --within ../master-long.mp3
Offset: 239.056 (seconds)
Standard score: 21.03329233999636

audio-offset-finder --find-offset-of ../sample.mp3 --within ../master-short.mp3
Offset: 4.112 (seconds)
Standard score: 4.302494155871559
```

As you can see, the score in the sort file is 4.3 while it is 21 in the long file, with exactly the same waveform.

Now, my usage scenario:
I search for a small part of a song in a long recording of a night. I don't know when the song started, and I don't know when the song stopped. After finding one piece (20s duration, starting from minute 2 of that song), I try to skip forward and backward (let's say one minute) and check if that sample (20s duration, starting from minute 3) is findable someware around the last offset+60s, and so on. Unfortunately, I don't have a threshold anymore. Before, it was 21, so I thought the new finding should be good if it has at least 70% of the old score, which is 12.6. But 4.3 is so low that it doesn't look anymore like a match.

Another sample of 10s, with no relevance to the given files, gives me a score of 6 and 1.7

```
audio-offset-finder --find-offset-of ../sample2.mp3 --within ../master-long.mp3
Offset: 209.056 (seconds)
Standard score: 6.053836525077971

audio-offset-finder --find-offset-of ../sample2.mp3 --within ../master-short.mp3
Offset: 4.432 (seconds)
Standard score: 1.7786410969164623
```

So, 4.3 means "match" on the short master while 6 is still a "no match" on the long master. How can I ever trust such a score?

**Comment by stephenjolly** [comment]
So, here's the cross-correlation plot for the long master:
![cc-long](https://user-images.githubusercontent.com/10116978/166449453-d11e975c-03aa-4292-81f0-0f162064af54.png)

And here's the same for the short one:
![cc-short](https://user-images.githubusercontent.com/10116978/166449524-d1b4aa3e-017f-4268-8052-fd82ef73c998.png)

The scores in this instance are just reflecting the underlying reality, that the prominence of the correlation peak is much lower.  I think this is because the comparison against the longer master uses roughly twice as many correlation frames, so the "background noise" of uncorrelated offsets is pushed down by the additional unrelated audio in the cross-correlations.

Can you increase the length of the audio in your "short" scans, and see if that improves the scores?

**Comment by daald** [comment]
Not sure which file you mean to make longer, but if I simplify the `correl_nframes` formula to `len(mfcc2)` I get the following values:

```
audio-offset-finder --find-offset-of ../sample.mp3 --within ../master-long.mp3
Offset: 239.056 (seconds)
Standard score: 21.03329233950164

audio-offset-finder --find-offset-of ../sample.mp3 --within ../master-short.mp3
Offset: 4.112 (seconds)
Standard score: 3.7772447884214406

audio-offset-finder --find-offset-of ../sample-nomatch-silence.mp3 --within ../master-long.mp3
Offset: 236.784 (seconds)
Standard score: 8.34786658045298

audio-offset-finder --find-offset-of ../sample-nomatch-silence.mp3 --within ../master-short.mp3
Offset: 3.088 (seconds)
Standard score: 2.6384668533300206

audio-offset-finder --find-offset-of ../sample-nomatch-440hz.mp3 --within ../master-long.mp3
Offset: 241.504 (seconds)
Standard score: 8.467720427577177

audio-offset-finder --find-offset-of ../sample-nomatch-440hz.mp3 --within ../master-short.mp3
Offset: 3.568 (seconds)
Standard score: 3.1921615790106657
```

master-short scores go up, master-long scores are stable. no wonder, correl_nframes was 392 for master-short and is 626 after the change, same as for master-long where the value was already 626.

**Comment by stephenjolly** [comment]
I meant make the "master_short" input file (and its equivalents in your private dataset) longer.  But not as long as master-long.  As I understand it their current lengths are 18s and 10m - maybe a 1 minute long file?

Interesting to see the improvement you get by changing the calculation of correl_nframes though.

**Comment by stephenjolly** [comment]
That's what I expected, so it's good that your experiments appear to confirm that.

Does that knowledge give you a way to use the tool to achieve your intended goals?
