### ISSUE TITLE
negative dimensions not allowed

### ISSUE THREAD

**Issue by PaulDDD** [bbc/audio-offset-finder#3]
Hello

Am getting this report when running on OSX:

Traceback (most recent call last):
  File "/usr/local/bin/audio-offset-finder", line 39, in <module>
    main()
  File "/usr/local/bin/audio-offset-finder", line 34, in main
    offset, score = find_offset(args.within, args.find_offset_of, args.sr, args.trim)
  File "/Library/Python/2.7/site-packages/audio_offset_finder/audio_offset_finder.py", line 40, in find_offset
    c = cross_correlation(mfcc1, mfcc2, nframes=correl_nframes)
  File "/Library/Python/2.7/site-packages/audio_offset_finder/audio_offset_finder.py", line 60, in cross_correlation
    c = np.zeros(n)
ValueError: negative dimensions are not allowed

Any ideas?

**Comment by Davidhw** [comment]
My work-around for this problem was to import find_offset from audio_offset_finder and call find_offset(file1, file2, correl_nframes=700). correl_nframes defaults to 1000, which is too big for some files.

**Comment by jaypinho** [comment]
I just tried this now (made correl_nframes=300 because even 700 was apparently too large for my 4- and 8-second audio files). But now I get this:

```
Traceback (most recent call last):
  File ".../audio_offset_finder.py", line 87, in <module>
    find_offset('test_full.wav', 'test_part.wav')
  File ".../audio_offset_finder.py", line 43, in find_offset
    c = cross_correlation(mfcc1, mfcc2, nframes=correl_nframes)
  File ".../audio_offset_finder.py", line 65, in cross_correlation
    cc = np.sum(np.multiply(mfcc1[k:k+nframes], mfcc2[:nframes]), axis=0)
ValueError: operands could not be broadcast together with shapes (300,26) (241,26)
```

(Note that I am using @stephenjolly's PR #14 for this.)

Is there documentation somewhere explaining what each of these parameters (e.g. correl_nframes, hop_length, win_length, etc.) is/does?

**Comment by stephenjolly** [comment]
Try correl_nframes=200?  I think that maybe even 300 is too high for your shorter input file.

On 16 Apr 2022, at 11:09, Jay Pinho ***@***.***> wrote:

﻿

I just tried this now (made correl_nframes=300 because even 700 was apparently too large for my 4- and 8-second audio files). But now I get this:

Traceback (most recent call last):
  File ".../audio_offset_finder.py", line 87, in <module>
    find_offset('test_full.wav', 'test_part.wav')
  File ".../audio_offset_finder.py", line 43, in find_offset
    c = cross_correlation(mfcc1, mfcc2, nframes=correl_nframes)
  File ".../audio_offset_finder.py", line 65, in cross_correlation
    cc = np.sum(np.multiply(mfcc1[k:k+nframes], mfcc2[:nframes]), axis=0)
ValueError: operands could not be broadcast together with shapes (300,26) (241,26)


(Note that I am using @stephenjolly<https://github.com/stephenjolly>'s PR #14<https://github.com/bbc/audio-offset-finder/pull/14> for this.)

Is there documentation somewhere explaining what each of these parameters (e.g. correl_nframes, hop_length, win_length, etc.) is/does?

**Comment by jaypinho** [comment]
Thank you! I got a value back this time. Is `correl_nframes` basically the number of discrete chunks the file is chopped into for comparison?

**Comment by stephenjolly** [comment]
This should now be fixed - the code now works down to very short audio file lengths, as of commit https://github.com/bbc/audio-offset-finder/commit/087d805b457b8e833677b6fbff5d4702678a83bc

**Comment by stephenjolly** [comment]
hop_length determines the number of samples that the algorithm hops forward between generating each MFCC frame, so the total number of frames is roughly the length of the file in samples (post-resembling) divided by the hop length. (Frames are generated from overlapping sets of samples, so the hop length is smaller than the FFT size.)

win_length is the length of the window function to apply to the audio samples prior to Fourier-transforming them during the MFCC calculation.

correl_nframes is the number of MFCC frames to use in the cross-correlation, so it must be <= the numbers of frames that have been calculated for each input or the algorithm will run out of frames.

**Comment by stephenjolly** [comment]
hop_length determines the number of samples that the algorithm hops forward between generating each MFCC frame, so the total number of frames is roughly the length of the file in samples (post-resembling) divided by the hop length. (Frames are generated from overlapping sets of samples, so the hop length is smaller than the FFT size.)

correl_nframes is the number of MFCC frames to use in the cross-correlation, so it must be <= the numbers of frames that have been calculated for each input or the algorithm will run out of frames. (There might be an additional complexity here due to zero-padding, but it’s a holiday weekend in the UK and I don’t have the code in front of me.)

On 16 Apr 2022, at 15:04, Jay Pinho ***@***.***> wrote:

﻿

Thank you! I got a value back this time. Is correl_nframes basically the number of discrete chunks the file is chopped into for comparison?
