### ISSUE TITLE
Update docs to include `setuptools` install

### ISSUE THREAD

**Issue by Sawtaytoes** [bbc/audio-offset-finder#48]
I had to manually install `setuptools` on a fresh Python install on Windows or else this gave me some cryptic "ModuleNotFoundError: No module named 'pkg_resources'" error:
```sh
pip install setuptools
```

If it weren't for ChatGPT, I would've been completely lost.

**Comment by stephenjolly** [comment]
Hi Kevin - many thanks for letting us know about this issue.  I'd like to look into it some more and maybe see if I can reproduce it.  If it's a problem with our installation process, then we'll want to look into updating our automated tests as well as the documentation.  Could you provide some information to help us look into things further?

- The version of Windows that you're using
- The version of Python that you're using
- Where you got your Python installer from
- Whether you're using Python virtual environments or similar to manage package versions.

Thanks again for reporting this.

**Comment by Sawtaytoes** [comment]
- Windows 11 (64-bit)
- Python 3.12.?
- I got it from the website, but when I went to run the CLI command, it made me download it from the Microsoft Store:
![image](https://github.com/bbc/audio-offset-finder/assets/3948069/94b2967c-a7ae-4453-8355-afd3cf70ea61)
- I don't know what Python virtual environments are. The only reason I've ever had Python installed is it's used in some Node.js packages (if that helps).

**Comment by stephenjolly** [comment]
Thanks for the additional info.  My initial thought is that this is likely to be a Python 3.12 issue rather than a Windows one, and another thing we should think about is being a bit more explicit about which Python versions we officially support.  It only became possible to install the tool on Python 3.12 in the last few days - prior to that one of the libraries we depend on ("numba") didn't support the new Python version.  So my next step will be to get our automated tests working under Python 3.12 on Windows, MacOS and Linux and then review the documentation after that.

**Comment by stephenjolly** [comment]
Installing setuptools fixes the failed builds in #47 so this does indeed appear to be the problem.  TODO: review documentation.

**Comment by stephenjolly** [comment]
This will be fixed in #50.
